config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  root "top#index"
  resources :users, only: %i(index show)
  get '/posts' => 'top#index'
  resources :posts, only: %i(show create destroy) do
    resources :comments, only: %i(create destroy)
  end
  resources :shops, only: %i(index)
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  resources :notifications, only: %i(index)
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if user_signed_in?
      @post = current_user.posts.build
      user = User.find(current_user.id)
      follow_users = user.following
      timeline = Post.where(id: user.posts.last).or(Post.where(user_id: follow_users.ids))
      if follow_users.any?
        @timeline = timeline.order(created_at: :desc).paginate(page: params[:page], per_page: 40)
      else
        @timeline = Post.order(created_at: :desc).paginate(page: params[:page], per_page: 40)
      end
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/index.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
      <%= link_to user_path(current_user.id) do %>
        <i class="fas fa-user-edit fa-3x userPost_link">編集ページへ</i>
      <% end %>
      <div class="userPost">
        <div class='userPost_img'>
          <% if current_user.image? %>
            <%= image_tag(current_user.image.url(:thumb), :size =>'150x150') %>
          <% else %>
            <%= image_tag 'no-image.png', :size =>'150x150' %>
          <% end %>
        </div>
        <div class='userPost_name'>
          <%= current_user.name %>
        </div>
        <%= link_to shops_path, class: "userPost_form_shop_link" do %>
          お店を探す<i class="fas fa-store fa-2x userPost_form_shop_icon"></i>
        <% end %>
        <div class='userPost_form'>
          <%= form_for(@post) do |f| %>
            <%= f.label :picture, class: "userPost_form_images",for: "file_photo" do %>
              <i class="fas fa-images fa-3x userPost_form_images_icon" data-toggle="tooltip" data-placement="bottom" title="ファイル形式は jpg, jpeg, gif, pngのみ可能です"></i>
              <p><%= f.file_field :picture, id: "file_photo" %></p>
            <% end %>
            <div class="userImgPreview" id="userImgPreview">
              <img id="thumbnail" class="userImgPreview_content" accept="image/*" src="">
            </div>
            <p class="form-group">
              <%= f.text_area :content, placeholder: "Let's Share！ (200文字以内で入力してください)", class: "form-control" %>
            </p>
            <p><%= f.submit "送信", class: "btn btn-warning btn-lg userPost_form_botton" %></p>
          <% end %>
        </div>
      </div>
      </div>  
      <div class="col-md-6">
        <% if current_user.posts.any? %>
          <table class="table Main_Light_section">
            <thead>
              <tr>
                <% if @timeline.any? %>
                <p class="MainPagination"><%= will_paginate @timeline %></p>
                  <th>つぶやき</th>
                <% end %>
              </tr>
            </thead>
            <tbody class="Light_Section">
              <% @timeline.each do |post| %>
                <tr>
                  <td class="User_icon">
                    <ul>
                      <li>
                        <% if post.user.image? %>
                          <%= image_tag post.user.image.url(:thumb), :size =>'80x80', class: "User_icon_image" %>
                        <% else %>
                          <%= image_tag 'no-image.png', :size =>'80x80', class: "User_icon_image" %>
                        <% end %>
                      </li>
                      <li><%= link_to "#{post.user.name}", post.user, class: "User_icon_name" %></li>
                      <% if post.user == current_user %>
                        <li>
                          <%= link_to post, method: :delete, data: { confirm: "本当に削除しますか？" } do %>
                            <i class="far fa-trash-alt fa-2x User_icon_delete">削除する</i>
                          <% end %>  
                        </li>
                      <% end %>
                    </ul>
                  </td>
                  <td class="Timeline">
                    <ul class="Timeline_box">
                      <li class="Timeline_content"><%= Rinku.auto_link(simple_format(post.content), :all, 'target="_blank"').html_safe %></li>
                      <% if post.picture? %>
                        <li class="Timeline_Image"><%= image_tag post.picture.url, :size =>'300x300' %></li>
                      <% end %>
                      <% if post.gurunabi_image? %>
                        <li><%= Rinku.auto_link(simple_format(post.gurunabi_image), :all, 'target="_blank"').html_safe %></li>
                      <% end %>
                      <%= link_to post_path(post.id) do %>
                        <i class="fas fa-comment-dots Timeline_comment_link">コメントする</i>
                      <% end %>
                    </ul>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="loginPage">
    <div class="container">
      <div class="loginPage_contents">
        <h1 class="h4 loginPage_contents_title">Restaurant Share</h1>
        <%= image_tag 'ryourinin.png', class: 'loginPage_contents_TopImage' %>
        <%= link_to "メールアドレスでログインする", new_user_session_path, class: "btn loginPage_contents_btn" %>
        <%= link_to "Facebookでログインする", user_facebook_omniauth_authorize_path, class: "loginPage_facebook" %>
        <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "loginPage_guestlogin" %>
      </div>
    </div>
  </div>
<% end %>
<%= render 'layouts/footer' %>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>