config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  root "top#index"
  resources :users, only: %i(index show)
  get '/posts' => 'top#index'
  resources :posts, only: %i(show create destroy) do
    resources :comments, only: %i(create destroy)
  end
  resources :shops, only: %i(index)
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  resources :notifications, only: %i(index)
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  validates :name, presence: true
  validates :self_introduction, length: { maximum: 300 }

  mount_uploader :image, ImageUploader
  enum sex: { 男: 0, 女: 1 }
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # omniauthの設定
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    user ||= User.create(
      uid: auth.uid,
      provider: auth.provider,
      email: auth.info.email,
      name: auth.info.name,
      password: Devise.friendly_token[0, 20],
      remote_image_url: auth.info.image
    )

    user
  end

  # パスワード入力なしでプロフィール更新
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  # 名前での検索機能
  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end

  # フォロー機能
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: 'Guest') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  def check_guest
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i(update destroy)

  def after_sign_up_path_for(resource)
    root_path
  end

  def after_update_path_for(resource)
    user_path(@user.id)
  end

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.paginate(page: params[:page], per_page: 20).search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page], per_page: 20)
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<%  unless current_user == @user %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
      html: { method: :delete }) do |f| %>
        <%= f.submit "フォロー中", class: "btn unfollow_botton" %>
      <% end %>
    <% else %>
      <%= form_for(current_user.active_relationships.build) do |f| %>
        <div><%= hidden_field_tag :followed_id, @user.id %></div>
        <%= f.submit "フォロー", class: "btn follow_botton" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render 'layouts/header' %>
<div class="AllUsersPage">
  <h1 class="AllUsersPage_toptitle">All Users</h1>
  <%= form_tag(users_path, :method => "get", :class => 'AllUsersPage_search_form') do %>
    <%= text_field_tag :search, "",{ placeholder: "名前で探す", size: "30" } %> 
    <%= button_tag type: 'submit', :name => nil, class: 'btn btn-default' do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %> 
  <p class="AllUsersPage_mypagelink">
    <%= link_to "←マイページに戻る", user_path(current_user.id) %>
  </p>
  <%= will_paginate @users, previous_label: '&lt 前へ', next_label: '次へ &gt' %>
  <table class="table table-striped UsersItem">
    <thead class="UsersItem_title">
      <tr class="UsersItem_title_name">
        <th class="UsersItem_title_name_lest1">User</th>
        <th class="UsersItem_title_name_lest2">名前</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="UsersItem_imgs">
            <% if user.image? %>
              <%= link_to image_tag(user.image.url(:thumb), :size =>'150x150'), user %>
            <% else %>
              <%= link_to image_tag('no-image.png', :size =>'150x150'), user %>
            <% end %>
          </td>
          <td class="UsersItem_name"><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'layouts/footer' %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>
<div class='usershowPage'>
  <div class='container'>
    <div class="row">
      <div class="col-md-6 usershowPage_leftItem">
        <header class="header">
          <div class='userAction_index userAction_common'>
            <%= link_to(users_path, class: "User_List") do %>
              <i class="fas fa-reply-all fa-2x"></i>
            <% end %>
            <span class="userAction_label">User一覧</span>
          </div>
        </header>
        <div class='userInfo'>
          <div class='userInfo_img'>
            <% if @user.image? %>
              <%= image_tag @user.image.url(:thumb) %>
            <% else %>
              <%= image_tag 'no-image.png', :size =>'170x170' %>
            <% end %>
          </div>
          <div class='userInfo_name'><%= @user.name %></div>
          <div class="userInfo_follow">
            <a href="<%= following_user_path(@user) %>">
              フォロー中 <%= @user.following.count %>
            </a>
            <a href="<%= followers_user_path(@user) %>">
              フォロワー <%= @user.followers.count %>
            </a>
            <%= render 'follow_form' %>
          </div>
          <div class='userInfo_selfIntroduction'><%= @user.self_introduction %></div>
        </div>
        <% if current_user.id == @user.id %>
          <div class='PostBtton'>
            <div class='PostBtton_item'>
              <%= link_to(root_path, class: "User_post") do %>
                <i class="fas fa-images fa-2x"></i>
              <% end %>
              <span>投稿する</span>
            </div>
          </div>
          <div class='userAction'>
            <div class="userAction_edit userAction_common">
              <%= link_to(edit_user_registration_path, class: "User_edit") do %>
                <i class="fas fa-edit fa-2x"></i>
              <% end %>
              <span>情報を編集</span>
            </div>
            <div class='userAction_logout userAction_common'>
              <%= link_to(destroy_user_session_path, method: :delete, class: "User_delete") do %>
                <i class="fas fa-cog fa-2x"></i>
              <% end %>
              <span>ログアウト</span>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        <% if @user.posts.any? %>
          <table class="table table-condensed">
            <thead>
              <tr>
                <th>つぶやき</th>
                <th class="MainPagination"><%= will_paginate @posts %></th>
              </tr>
            </thead>
            <tbody class="Light_Section">
              <% @posts.each do |post| %>
                <tr>
                  <td class="User_icon">
                    <ul>
                      <li>
                        <% if @user.image? %>
                          <%= image_tag @user.image.url(:thumb), :size =>'80x80', class: "User_icon_image" %>
                        <% else %>
                          <%= image_tag 'no-image.png', :size =>'80x80', class: "User_icon_image" %>
                        <% end %>
                      </li>
                      <% if current_user.id == @user.id %>
                        <li><%= link_to "削除する", post, method: :delete,:class=>"User_icon_delete", data: { confirm: "本当に削除しますか？" } %></li>
                      <% end %>
                    </ul>
                  </td>
                  <td class="Timeline">
                    <ul class="Timeline_box">
                      <li class="Timeline_content"><%= Rinku.auto_link(simple_format(post.content), :all, 'target="_blank"').html_safe %></li>
                      <% if post.picture? %>
                        <li class="Timeline_Image"><%= image_tag post.picture.url, :size =>'300x300' %></li>
                      <% end %>
                      <% if post.gurunabi_image? %>
                        <li><%= Rinku.auto_link(simple_format(post.gurunabi_image), :all, 'target="_blank"').html_safe %></li>
                      <% end %>
                      <%= link_to post_path(post.id) do %>
                        <i class="fas fa-comment-dots Timeline_comment_link">コメントする</i>
                      <% end %>
                    </ul>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/users/show_follow.html.erb
<%= render 'layouts/header' %>
<div class="FollowPage">
  <div class="row">
    <div class="col-md-6 FollowPage_left">
      <div class="UserInformation">
        <p class="UserInformation_link"><%= link_to "プロフィールページへ", @user %></p>
        <% if @user.image? %>
          <%= image_tag @user.image.url, :size =>'200x200', class: "UserInformation_image" %>
        <% else %>
          <%= image_tag 'no-image.png', :size =>'200x200', class: "UserInformation_image" %>
        <% end %>
        <h3 class="UserInformation_name"><%= @user.name %></h3>
      </div>
      <div class="UserFollow">
        <% if @users.any? %>
          <ul class="UserFollow_link">
            <li><a href="<%= following_user_path(@user) %>">フォロー中 <%= @user.following.count %></a></li>
            <li><a href="<%= followers_user_path(@user) %>">フォロワー <%= @user.followers.count %></a></li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-md-6 FollowPage_right">
      <h3 class="FollowPage_right_title"><%= @title %></h3>
      <% if @users.any? %>
        <ul class="FollowPage_right_item">
          <%= will_paginate %>
          <% @users.each do |user| %>
            <li class="FollowPage_right_list">
              <% if user.image? %>
                <%= image_tag user.image.url, :size =>'50x50', class: "FollowPage_right_image" %>
              <% else %>
                <%= image_tag 'no-image.png', :size =>'50x50', class: "FollowPage_right_image" %>
              <% end %>
              <span class="FollowPage_right_name">
                <%= link_to user.name, user_path(user.id) %>
              </span>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>