config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }
  root "top#index"
  resources :users, only: %i(index show)
  get '/posts' => 'top#index'
  resources :posts, only: %i(show create destroy) do
    resources :comments, only: %i(create destroy)
  end
  resources :shops, only: %i(index)
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: %i(create destroy)
  resources :notifications, only: %i(index)
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">close</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">close</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  	<p>©︎2020 TAKURO INOUE</p>
</footer>

app/views/layouts/_header.html.erb
<header id="CommonHeader">
    <p>
      <%= link_to "Restaurant Share", root_path %>
      <span class="notification">
        <% unchecked_notifications = current_user.passive_notifications.where(checked: false) %>
        <%= link_to notifications_path, class: "notification_page_link" do %>
          <% if unchecked_notifications.any? %>
            <i class="fas fa-bell animate__animated animate__swing"></i>
          <% else %>
            <i class="fas fa-bell"></i>
          <% end %>
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle notification-circle">お知らせ</i>
          <% end %>
        <% end %>
      </span>
    </p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant Share</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
  </head>
  <body>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>